name: list_combinations
description: Generates all combinations of a list.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-5.0.dev <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
